Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.ssh.insert_key = false

  config.vm.define 'srv' do |srv|
  	srv.vm.provision "ansible" do |ansible|
    	ansible.verbose = "v"
    	ansible.playbook = "playbook.yml"
    	ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
  	end
  end
end
